configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-38828e84cd9dfc8567eeb81a18d74cb05ecd1fae14be6e3c5a55ea3a241403ed.yml
