configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-823979c3b3f140573999a7fe6ffdbd0133d9d47de1520ee8a82dda8f088a4fa1.yml
