configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-ac4fa65bb5fa17856ec6c70e6bd7427531eeeec184af5eef4233650d205ffc85.yml
