configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-28f1b9caacf5932b7232ffaf537ba86afb1b149cc4ba0d655c2629e78ad9bdc6.yml
openapi_spec_hash: 1a572be4d95ea0b245d0e0c8d42faf6f
config_hash: 19115bda688fa63841952001e02a0bdf
