configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d01d67433674d559bd270d181ac6a71bf9d67d257e454917773d5701134a487b.yml
