configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-1ac213a5a7d438380cac036781d8e8861948e74f170d355658c14c88598bc7f5.yml
