configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-37fec001337110666d2c394a280cbced5aba99315c82ebfa8cda94bd78419f6e.yml
