configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-b2434c32d820250244d9dcc451a488392e0fb6ecfa771f506e7accf658bb9cb5.yml
