configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-e5f98ee3eb00fd59d9dfe35d3ae3ee9ac74bd9ce2c8cf3cbb765ee6781fd647e.yml
openapi_spec_hash: 85e2dcdb4be08bf6a8ca3ca54abda38e
config_hash: 19115bda688fa63841952001e02a0bdf
