configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-e2e2f6f80021070be059fb7f1e96e44504f27f911054602b1c8108a694c116fa.yml
