configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-558def1a5ef301c112650a1a50e68dde9f549e84dc3a557d15884dd877e0d059.yml
