configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-88081f43e9edfec8fc8edcc24dc3ec6a6bd8422a6698deb4501088c9ba9ed386.yml
