configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-a806cccbb3baa34144faebcadca31482d37aa796388b09570eba4804e09c07e6.yml
