configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-c03f59060d07a2aba243c87a21eb95eecd3ee3937a4f674d11d02342a8e3ccd0.yml
