configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-8a6f352feee9b900dba951935200caca5085575a38188872726c1753b6252877.yml
