configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-b0f9548ee04fbb7951651855140e61a0ed90ff0c27981aaad91cb4ff095909cc.yml
