configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-ff1e26771cd34b92d185ccf18a4b87e446bff0517531cc31ff13e42e516af98a.yml
