configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-0c3c86a0d3aef4d8e2b64ef107fb18f88ad43dd935cd5687c5ecb5562691cc6a.yml
