configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-0b25065ea610830ff46af9d96b474107b1cdaa4898c9790f55b76fd3a5df09f7.yml
