configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-c387aad50d8cd38957d4b0d17e2c6e24c914e2ad7625fad813a3579e2ca0cc53.yml
