configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-7e75c690ca3a09202ccac01df384146350323a0254c3db4377619aeb072c051b.yml
