configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-e3e1d93cfe2a7d30863fca43965f9f17ef97af9e9e1f3a004e1896a692c91fd1.yml
