configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-26cb93e8e39e25896c1b21d0c878541c646dd5ac14e2d08ad71bb052d6b15ae4.yml
