configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-af8bb17d060c46d117d40b1251f4ed07fe8885c0e075ef0ec5c3333d859e5e57.yml
