configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-86f6011ef92bd85a075100bd8b34fce3a5bbafefac36a4d144cfa72c1d881661.yml
