configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d2eb179091defb06dbc59bbfbb5e39e04a6040d9e3a07e040cd4b04f6406876c.yml
