configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-3555d7698a1087c92e58dddf801b823db026d4583c995c8553d18820367ca09d.yml
