configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-51a2544539adeef60f4f3d3b9b6a96dc0deb3e37af9352f9704d668b52713671.yml
