configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-5cc68d2b9c51a25e533d872aab78b56dccfa9749968483865ae4869d632dcce3.yml
