configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-92ba3e1201d9ffde0ce175672333631202669c7094a46970629963a6f8dedbf5.yml
