configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-fb0a15a9b4559ffef4d1bd40719ba2e4b631db7cbefb3456b7ba5b156c8d273a.yml
