configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-e6dbaf4ff0715e2920841f1f385b91476021869a5fe06fadcea60269cb613a45.yml
