configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-47879dec3f0ebadf761e759bcbe7684db32bec6aee58a9a66a4cd6ae1d86e05e.yml
