configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-2cc87c2012acd04d7aae50588f13f999d10f7f2bf12e1726ef1c0b4cd3c86d8c.yml
