configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-9816fe64b2ff9d2444833d927889d2483378f701f4d677fdd43db192c1ed0692.yml
