configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-14745ac981c759a60c7377fee218ace78e9dd1ab079def13f99257f52b260be3.yml
