configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d762cc7dfd0329b91f20a3d83df0f6e1276447dec45d6f6767cde14d8a8c2bd5.yml
