configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-4e518b04a4babeebdae0cd40c7dca855315aca116f11e4c932bd9d86c83bb76d.yml
