configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-a2e97f5b8b75fc996e41f4634161a53be717227902dd378e0d4a6f2deeb10b69.yml
