configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-7034afb592aa0f99b0147eafc9f5e41bb7922c464cf4efa1897c3f712811cfbf.yml
