configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d8727d763e6cd235f00e15a31171657199204d90f4e0679774090c60497acaad.yml
