configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-5c2d2fb2581d15bf95b083c3f35ff0f8c873f0986515ae6642f064b2d2a8241b.yml
