configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/roark-innovations-inc%2Froark-analytics-d9323c00115c8790fababddacb91f86c0990221e7208e6daa661560f32057ab6.yml
