// Generated by scripts/sync-version.cjs from this package's package.json, which
// the build runs before tsc. Do not edit: an edit here is overwritten, and the
// published number is whatever package.json says.
//
// It exists at all because the CLI is not in release-please-config.json's
// `extra-files` - it ships from publish-cli.yml rather than the vendor's
// release train - so nothing else keeps this in step.
export const version = '0.2.0';
